// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StateShared`

RqbitDesktopConfig readConfig({required String path}) =>
    RustLib.instance.api.crateApiInitMainReadConfig(path: path);

void writeConfig({required String path, required RqbitDesktopConfig config}) =>
    RustLib.instance.api.crateApiInitMainWriteConfig(
      path: path,
      config: config,
    );

Api apiFromConfig({
  required InitLoggingResult initLogging,
  required RqbitDesktopConfig config,
}) => RustLib.instance.api.crateApiInitMainApiFromConfig(
  initLogging: initLogging,
  config: config,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Api>>
abstract class Api implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiError>>
abstract class ApiError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InitLoggingResult>>
abstract class InitLoggingResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<State>>
abstract class State implements RustOpaqueInterface {
  Api api();

  Future<void> configure({required RqbitDesktopConfig config});

  factory State({required InitLoggingResult initLogging}) =>
      RustLib.instance.api.crateApiInitMainStateNew(initLogging: initLogging);
}

class CurrentState {
  final RqbitDesktopConfig? config;
  final bool configured;

  const CurrentState({this.config, required this.configured});

  static Future<CurrentState> default_() =>
      RustLib.instance.api.crateApiInitMainCurrentStateDefault();

  @override
  int get hashCode => config.hashCode ^ configured.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CurrentState &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          configured == other.configured;
}
