// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

RqbitDesktopConfig readConfig({required String path}) =>
    RustLib.instance.api.crateApiMainInitReadConfig(path: path);

void writeConfig({required String path, required RqbitDesktopConfig config}) =>
    RustLib.instance.api.crateApiMainInitWriteConfig(
      path: path,
      config: config,
    );

Future<Api> apiFromConfig({
  required InitLoggingResult initLogging,
  required RqbitDesktopConfig config,
}) => RustLib.instance.api.crateApiMainInitApiFromConfig(
  initLogging: initLogging,
  config: config,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Api>>
abstract class Api implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiError>>
abstract class ApiError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InitLoggingResult>>
abstract class InitLoggingResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<State>>
abstract class State implements RustOpaqueInterface {
  Api api();

  InitLoggingResult get initLogging;

  set initLogging(InitLoggingResult initLogging);

  Future<void> configure({required RqbitDesktopConfig config});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<State> newInstance({required InitLoggingResult initLogging}) =>
      RustLib.instance.api.crateApiMainInitStateNew(initLogging: initLogging);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StateShared>>
abstract class StateShared implements RustOpaqueInterface {
  Api? get api;

  RqbitDesktopConfig get config;

  set api(Api? api);

  set config(RqbitDesktopConfig config);
}

class CurrentState {
  final RqbitDesktopConfig? config;
  final bool configured;

  const CurrentState({this.config, required this.configured});

  static Future<CurrentState> default_() =>
      RustLib.instance.api.crateApiMainInitCurrentStateDefault();

  @override
  int get hashCode => config.hashCode ^ configured.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CurrentState &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          configured == other.configured;
}
